In [76]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
X_train = pd.read_csv('row_X.csv', delimiter = ',')
X_train = StandardScaler().fit_transform(X_train)

In [85]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
pca.fit(X_train)
pca

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [86]:
print('singular value :', pca.singular_values_)
print('singular vector :\n', pca.components_.T)

singular value : [2847.15302591 2577.03431083 1667.05394653]
singular vector :
 [[-0.01188363 -0.15829419  0.32471742]
 [ 0.07062655 -0.26971809 -0.1127347 ]
 [ 0.1021387  -0.22585381 -0.14104571]
 [-0.00830832 -0.1878737   0.30758545]
 [ 0.06810561 -0.27102292 -0.12070493]
 [ 0.10282227 -0.24586269 -0.15117503]
 [ 0.00578411 -0.20542322  0.16234364]
 [ 0.06513819 -0.27109433 -0.1190724 ]
 [ 0.09313389 -0.24806251 -0.15273186]
 [ 0.23909308  0.0675806   0.03708874]
 [-0.00888184 -0.11171908  0.39695748]
 [ 0.07239507 -0.27182597 -0.05246363]
 [ 0.23079471  0.04603536 -0.05875807]
 [ 0.11009233 -0.25270194 -0.02911982]
 [ 0.24120165  0.06778943  0.03405157]
 [-0.11097579 -0.02382269  0.10804477]
 [-0.01126401  0.00581136  0.14260899]
 [ 0.24379786  0.06806911  0.0289206 ]
 [ 0.240521    0.03286518 -0.06224111]
 [ 0.2438042   0.06707465  0.01764879]
 [-0.09754756 -0.02382876  0.10719293]
 [-0.01801891  0.01865043  0.09195523]
 [ 0.21439812  0.03358738 -0.06382733]
 [ 0.21283815  0.061743

In [87]:
print('eigen_value :', pca.explained_variance_)
print('explained variance ratio :', pca.explained_variance_ratio_)

eigen_value : [12.28226157 10.06229682  4.21071677]
explained variance ratio : [0.25588006 0.20963087 0.08772313]


In [88]:
print('explained variance ratio :', pca.explained_variance_ratio_)


explained variance ratio : [0.25588006 0.20963087 0.08772313]


In [26]:
pca = PCA(n_components=0.95)
X_proj = pca.fit_transform(X_train)

print('principal component vec :\n', pca.components_.T)
#출처: https://excelsior-cjh.tistory.com/167 [EXCELSIOR]

principal component vec :
 [[-9.91682800e-17]
 [-1.11022302e-16]
 [-1.82388826e-14]
 [-3.60275469e-15]
 [-1.21106003e-16]
 [-2.06114633e-14]
 [-1.65682372e-14]
 [-1.20974761e-16]
 [-2.12186791e-14]
 [-1.69415284e-15]
 [-1.23243112e-16]
 [-1.24758020e-16]
 [-3.05501517e-18]
 [-1.36729749e-16]
 [-1.72471138e-15]
 [ 1.64142336e-16]
 [ 1.10971540e-21]
 [-1.72376208e-15]
 [-5.76619770e-18]
 [-1.57846954e-15]
 [ 1.99109210e-16]
 [-4.49217079e-21]
 [-7.36337605e-18]
 [-1.67623513e-15]
 [ 7.73265025e-17]
 [-1.12296313e-20]
 [-1.23243112e-16]
 [-9.46380987e-10]
 [ 6.20526544e-03]
 [ 6.75844584e-01]
 [-1.38801279e-14]
 [ 7.37018041e-01]
 [-9.15483174e-18]
 [-1.24889453e-16]
 [-2.07438838e-18]
 [-1.31374627e-16]
 [-7.15645358e-16]
 [-1.14908201e-16]
 [-1.93783737e-21]
 [-2.48037638e-16]
 [-2.65594073e-18]
 [-7.36531549e-16]
 [-8.23698424e-17]
 [-1.42184476e-21]
 [-1.41334671e-15]
 [-3.03827503e-18]
 [-9.41915096e-16]
 [-5.81202074e-17]]


In [82]:
#차원축소
pca = PCA(n_components=1)
X_reduced = pca.fit_transform(X_train)  # PCA 계산 후 투영
print('선택한 차원(픽셀) 수 :', pca.n_components_)


선택한 차원(픽셀) 수 : 1


In [69]:
X_reduced.shape

(660000, 1)

In [52]:
X_reduced

array([[-4.13628420e+16, -4.53689736e+14, -6.78252035e+13,
        -6.80071643e+08,  1.56690436e+04],
       [-4.13905769e+16, -4.78812950e+14, -7.11523642e+13,
         8.27484382e+08,  2.33054351e+04],
       [-4.13730351e+16, -4.62870444e+14, -6.90406760e+13,
        -6.80109307e+08,  1.55827291e+04],
       ...,
       [-4.13905769e+16, -4.78812950e+14, -7.11523647e+13,
         8.27484895e+08,  2.79205612e+04],
       [-4.09202969e+16, -3.19377894e+14, -5.18814935e+13,
        -6.79242803e+08,  1.54281069e+04],
       [-4.13654358e+16, -4.55976998e+14, -6.81276838e+13,
        -6.80081078e+08,  1.04591831e+04]])

In [53]:
#차원복원
X_recovered = pca.inverse_transform(X_reduced)


In [73]:
Y_train = pd.read_csv('row_Y.csv', delimiter = ',')
Y_train = pd.factorize(Y_train.x)[0]

In [55]:
from sklearn.linear_model import LogisticRegression

log_clf = LogisticRegression() 
log_clf.fit(X_reduced,Y_train) 
log_clf.score(X_reduced, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.14845

In [56]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler



In [83]:
model = Sequential()
model.add(Dense(1, input_shape=[1], activation = 'relu'))
model.add(Dense(11, activation='softmax'))
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 3)                 6         
_________________________________________________________________
dense_12 (Dense)             (None, 11)                44        
Total params: 50
Trainable params: 50
Non-trainable params: 0
_________________________________________________________________


In [84]:
model.fit(X_reduced, Y_train, epochs=1) # 차원개수 1

660000/660000 [==============================] - 60s 90us/sample - loss: 1.5478 - acc: 0.3785s - l


In [ ]:
model.fit(X_reduced, Y_train, epochs=1) # 차원개수 1개