In [22]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix

from sklearn.svm import SVC

X = pd.read_csv('minimum2.csv', delimiter = ',')
Y = pd.read_csv('minimum_C.csv', delimiter = ',')

In [23]:
gamma = [10, 1, 0.1, 1e-5, 1e-4, 1e-5] # 4 0-4
cost = [0.001, 0.10, 0.1, 10, 25, 50, 100, 1000] #8 40 30 2-6

In [3]:
for i in range(1,4):
    for j in range(2,5):
        print("gamma: ", gamma[i], ", cost: ", cost[j])
        model = SVC(kernel='rbf', C= cost[j], random_state=0, gamma=gamma[i] )
        model.fit(X, Y.values.ravel())
        y_pred_svc = model.predict(X)
        print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
        print(confusion_matrix(Y, y_pred_svc))

gamma:  1 , cost:  0.1
Training Accuracy: 0.32
[[   0    0    0 2100    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0    0 3150    0    0    0    0    0    0    0    0]
 [   0    0    0 3150    0    0    0    0    0    0    0]
 [   0    0    0 3150    0    0    0    0    0    0    0]
 [   0    0    0 2100    0    0    0    0    0    0    0]
 [   0    0    0 2100    0    0    0    0    0    0    0]
 [   0    0    0 3150    0    0    0    0    0    0    0]
 [   0    0    0 3150    0    0    0    0    0    0    0]
 [   0    0    0 2100    0    0    0    0    0    0    0]
 [   0    0    0 2100    0    0    0    0    0    0    0]]
gamma:  1 , cost:  10
Training Accuracy: 0.81
[[2093    7    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0   57 3093    0    0    0    0    0    0    0    0]
 [   0  145    0 3005    0    0    0    0    0    0    0]
 [   0  498    0    0 2652    0    0

In [4]:
for i in range(0,4):
    for j in range(2,6):
        print("gamma: ", gamma[i], ", cost: ", cost[j])
        model = SVC(kernel='sigmoid', C= cost[j], random_state=0, gamma=gamma[i] )
        model.fit(X, Y.values.ravel())
        y_pred_svc = model.predict(X)
        print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
        print(confusion_matrix(Y, y_pred_svc))

gamma:  10 , cost:  0.1
Training Accuracy: 0.11
[[   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]]
gamma:  10 , cost:  10
Training Accuracy: 0.11
[[   0    0    0    0    0    0    0    0 2100    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    0    0    0    0   

Training Accuracy: 0.11
[[   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 3150    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]
 [   0 2100    0    0    0    0    0    0    0    0    0]]
gamma:  1e-05 , cost:  10
Training Accuracy: 0.11
[[   0    0    0    0    0    0    0    0 2100    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    

In [3]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.0001 )
model.fit(X, Y.values.ravel())
y_pred_svc = model.predict(X)
print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
print(confusion_matrix(Y, y_pred_svc))

model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.00001 )
model.fit(X, Y.values.ravel())
y_pred_svc = model.predict(X)
print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
print(confusion_matrix(Y, y_pred_svc))   

model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.000001 )
model.fit(X, Y.values.ravel())
y_pred_svc = model.predict(X)
print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
print(confusion_matrix(Y, y_pred_svc))       

Training Accuracy: 0.98
[[2094    0    6    0    0    0    0    0    0    0    0]
 [   0 3141    9    0    0    0    0    0    0    0    0]
 [   0    0 3150    0    0    0    0    0    0    0    0]
 [   0    0  137 3013    0    0    0    0    0    0    0]
 [   0    0  492    0 2658    0    0    0    0    0    0]
 [   0    0    0    0    0 2100    0    0    0    0    0]
 [   0    0    3    0    0    0 2097    0    0    0    0]
 [   0    0    0    0    0    0    0 3150    0    0    0]
 [   0    0    0    0    0    0    0    0 3150    0    0]
 [   0    0    2    0    0    0    0    0    0 2098    0]
 [   0    0    4    0    0    0    0    0    0    0 2096]]
Training Accuracy: 0.98
[[2095    0    5    0    0    0    0    0    0    0    0]
 [   0 3142    8    0    0    0    0    0    0    0    0]
 [   0    0 3150    0    0    0    0    0    0    0    0]
 [   0    0  104 3046    0    0    0    0    0    0    0]
 [   0    0  484    0 2666    0    0    0    0    0    0]
 [   0    0    0    0  

In [12]:
X_test = pd.read_csv('testset.csv', delimiter = ',')
Y_test = pd.read_csv('testset_C.csv', delimiter = ',')

In [13]:
X_test.shape, Y_test.shape, X.shape

((986750, 48), (986750, 1), (29400, 48))

In [14]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.0001 )
model.fit(X, Y.values.ravel())
y_pred_svc = model.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(Y_test, y_pred_svc))
print(confusion_matrix(Y_test, y_pred_svc))


Test Accuracy: 0.43
[[  3068  99127      0      0      0      0      0      0      0      0
       0]
 [     0  18000      0      0      0      0      0      0      0      0
       0]
 [     0  27550  32168      0      0      0      0      0      0      0
       0]
 [     0  12428      0  16640      0      0      0      0      0      0
       0]
 [     0  20397      0      0   9452      0      0      0      0      0
       0]
 [     0   3816      0      0      0 103869      0      0      0      0
       0]
 [     0  89811      0      0      0      0  32762      0      0      0
       0]
 [     0     89      0      0      0      0      0  92052      0      0
       0]
 [     0    106      0      0      0      0      0      0 105768      0
       0]
 [     0 231098      0      0      0      0      0      0      0   6567
       0]
 [     0  78151      0      0      0      0      0      0      0      0
    3831]]


In [18]:
X = pd.read_csv('goodratio_Min.csv', delimiter = ',')
Y = pd.read_csv('goodratio_Min_C.csv', delimiter = ',')


In [22]:
X.shape, Y.shape

((56400, 48), (56400, 1))

In [23]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.0001 )
model.fit(X, Y.values.ravel())

y_pred_svc = model.predict(X)
print('Test Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
print(confusion_matrix(Y, y_pred_svc))

y_pred_svc = model.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(Y_test, y_pred_svc))
print(confusion_matrix(Y_test, y_pred_svc))

Test Accuracy: 0.99
[[ 2100     0     0     0     0     0     0     0     0     0     0]
 [    0 30150     0     0     0     0     0     0     0     0     0]
 [    0     0  3150     0     0     0     0     0     0     0     0]
 [    0     0     0  3150     0     0     0     0     0     0     0]
 [    0   410     0     0  2740     0     0     0     0     0     0]
 [    0     0     0     0     0  2100     0     0     0     0     0]
 [    0     0     0     0     0     0  2100     0     0     0     0]
 [    0     0     0     0     0     0     0  3150     0     0     0]
 [    0     0     0     0     0     0     0     0  3150     0     0]
 [    0     0     0     0     0     0     0     0     0  2100     0]
 [    0     0     0     0     0     0     0     0     0     0  2100]]
Test Accuracy: 0.36
[[   873 101322      0      0      0      0      0      0      0      0
       0]
 [     0  18000      0      0      0      0      0      0      0      0
       0]
 [     0  59717      1      0      0

In [20]:
#first sampling
X = pd.read_csv('full.csv', delimiter = ',')
Y = pd.read_csv('full_C.csv', delimiter = ',')


In [21]:
X.shape, Y.shape

((1048575, 48), (1048575, 1))

In [24]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.0001 )
model.fit(X, Y.values.ravel())

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
X_test = pd.read_csv('goodratio_Min.csv', delimiter = ',')
Y_test = pd.read_csv('goodratio_Min_C.csv', delimiter = ',')

In [28]:
y_pred_svc = model.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(Y_test, y_pred_svc))
print(confusion_matrix(Y_test, y_pred_svc))

Test Accuracy: 0.76
[[  749  1351     0     0     0     0     0     0     0     0     0]
 [    0 30150     0     0     0     0     0     0     0     0     0]
 [    0  3149     1     0     0     0     0     0     0     0     0]
 [    0  3148     0     2     0     0     0     0     0     0     0]
 [    0  2054     0     0  1096     0     0     0     0     0     0]
 [    0    11     0     0     0  2089     0     0     0     0     0]
 [    0  1386     0     0     0     0   714     0     0     0     0]
 [    0     3     0     0     0     0     0  3147     0     0     0]
 [    0     3     0     0     0     0     0     0  3147     0     0]
 [    0  1372     0     0     0     0     0     0     0   728     0]
 [    0  1212     0     0     0     0     0     0     0     0   888]]


In [30]:
#no outlier learning
X = pd.read_csv('removeOutlier.csv', delimiter = ',')
Y = pd.read_csv('removeOutlier_C.csv', delimiter = ',')
X.shape, Y.shape

((584196, 48), (584196, 1))

In [ ]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.0001 )
model.fit(X, Y.values.ravel())

X_test = pd.read_csv('goodratio_Min.csv', delimiter = ',')
Y_test = pd.read_csv('goodratio_Min_C.csv', delimiter = ',')
y_pred_svc = model.predict(X_test)
print('Test Accuracy: %.2f' % accuracy_score(Y_test, y_pred_svc))
print(confusion_matrix(Y_test, y_pred_svc))

In [ ]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.0000001 )
model.fit(X, Y.values.ravel())
y_pred_svc = model.predict(X)
print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
print(confusion_matrix(Y, y_pred_svc))    

model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.00000001 )
model.fit(X, Y.values.ravel())
y_pred_svc = model.predict(X)
print('Training Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))
print(confusion_matrix(Y, y_pred_svc))      

In [ ]:
model2 = SVC(kernel='linear', C=1.0, random_state=0)
# 로지스틱 회귀에서의 C와 반대의 개념. 모델을 조율해주는 값이라고 보면 됨.
model2.fit(X, Y.values.ravel())
y_pred_svc = model2.predict(X)
print('Model1 Accuracy: %.2f' % accuracy_score(Y, y_pred_svc))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y, y_pred_svc)