In [1]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import numpy as np

import pydot
import mglearn

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
def model_test_acc(model):
    y_pred = model.predict(x_test)
    print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))  

In [ ]:
X_train.shape, Y_train.shape

In [ ]:
X_train = X_train.iloc[:,1:]
Y_train = Y_train.iloc[:,1]
Y_train = pd.factorize(Y_train)[0]

In [ ]:
X_train = StandardScaler().fit_transform(X_train)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( X_train , Y_train, test_size=0.1, random_state=42)

In [12]:
forest = RandomForestClassifier(n_estimators=5, random_state=2)
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=None,
            oob_score=False, random_state=2, verbose=0, warm_start=False)

In [21]:
forest.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=1872583848, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False,
             random_state=794921487, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_wei

In [13]:
print("훈련 세트 정확도: {:.3f}".format(forest.score(x_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(forest.score(x_test, y_test)))

훈련 세트 정확도: 0.909
테스트 세트 정확도: 0.909


In [14]:
y_pred = forest.predict(x_test)

In [15]:
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.91


In [16]:
print(confusion_matrix(y_test, y_pred)) 

[[5957    0    0    0    0    0    0    0    0    0    0]
 [   0 5773    0    0    0    0    0    0    0    0    0]
 [   0    0 5982    0    0    0    0    0    0    0    0]
 [   0    0    0 5989    0    0    0    0    0    0    0]
 [   0    0    0    0 5942    0    0    0    0    0    0]
 [   0    0    0    0    0 6009    0    0    0    0    0]
 [   0    0    0    0    0    0 6080    0    0    0    0]
 [   0    0    0    0    0    0    0 6099    0    0    0]
 [   0    0    0    0    0    0    0 5979    0    0    0]
 [   0    0    0    0    0    0    0    0    0 5876    0]
 [   0    0    0    0    0    0    0    0    0    0 6069]]


In [68]:
#X_temp = X_temp[["MI_dir_L3_mean","HH_jit_L3_mean"]].values
X_train.shape

(657547, 48)

In [16]:
print("훈련 세트 정확도: {:.3f}".format(forest.score(x_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(forest.score(x_test, y_test)))

훈련 세트 정확도: 0.909
테스트 세트 정확도: 0.908
