In [1]:
from thundersvm import SVC

In [19]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import numpy as np

from sklearn.externals import joblib 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [8]:
import pandas as pd 
X_train1 = pd.read_csv('mul_3_10000_X.csv', delimiter = ',')
Y_train1 = pd.read_csv('mul_3_10000_Y.csv', delimiter = ',')
#X_train2 = pd.read_csv('bi_3_X.csv', delimiter = ',')
#Y_train2 = pd.read_csv('bi_3_Y.csv', delimiter = ',')

In [9]:
X_train1 = X_train1.iloc[:,1:]
Y_train1 = Y_train1.iloc[:,1]
Y_train1 = pd.factorize(Y_train1)[0]

In [9]:
X_train2 = X_train2.iloc[:,1:]
Y_train2 = Y_train2.iloc[:,1]
Y_train2 = pd.factorize(Y_train2)[0]

In [10]:
X_train1 = StandardScaler().fit_transform(X_train1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [11]:
X_train2 = StandardScaler().fit_transform(X_train2)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [12]:
from sklearn.model_selection import train_test_split
x_train1, x_test1, y_train1, y_test1 = train_test_split( X_train1 , Y_train1, test_size=0.1, random_state=42)
#x_train2, x_test2, y_train2, y_test2 = train_test_split( X_train2 , Y_train2, test_size=0.2, random_state=42)

In [13]:
x_train1.shape

(9900, 48)

In [ ]:
model1 = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.1 )
model1.fit(x_train1, y_train1)
model1.save_to_file('./mul_3_10000')

In [14]:
model1 = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.01 )
model1.fit(x_train1, y_train1)
model1.save_to_file('./mul_3_10000')
model1_test_acc(model1)

In [16]:
y_pred=model1.predict(x_test1)

In [21]:
print('Accuracy: %.2f' % accuracy_score(y_test1, y_pred))

Accuracy: 0.87


In [17]:
confusion_matrix(y_test1,y_pred)

array([[ 97,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  97,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  89,   6,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  13,  99,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 106,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 101,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  90,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  88,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 100,   0,   0],
       [ 17,   0,   0,   0,   0,   0,   0,   0,   0,  71,  17],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   6, 103]],
      dtype=int64)

In [23]:
y_pred=model1.predict(x_test1)

In [24]:
print('Accuracy: %.2f' % accuracy_score(y_test1, y_pred))
confusion_matrix(y_test1,y_pred)

Accuracy: 0.89


array([[ 97,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  97,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  88,   7,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   5, 107,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 106,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 101,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  90,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  88,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 100,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,  86,  18],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   4, 105]],
      dtype=int64)

In [12]:
model1 = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.01 )
model1.fit(x_train1, y_train1)
#model1_test_acc(model1)

SVC(C=10, cache_size=None, class_weight={}, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma=0.01, gpu_id=0,
  kernel='rbf', max_iter=-1, max_mem_size=-1, n_jobs=-1, probability=False,
  random_state=0, shrinking=False, tol=0.001, verbose=False)

In [22]:
model1.save_to_file('./model1')

In [13]:
model2 = SVC(kernel='rbf', C= 1, random_state=0, gamma=0.01 )
model2.fit(x_train1, y_train1)

SVC(C=1, cache_size=None, class_weight={}, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma=0.01, gpu_id=0,
  kernel='rbf', max_iter=-1, max_mem_size=-1, n_jobs=-1, probability=False,
  random_state=0, shrinking=False, tol=0.001, verbose=False)

In [23]:
model2.save_to_file("./model2")

In [ ]:
model3 = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.01 )
model3.fit(x_train2, y_train2)

In [5]:
test = SVC(probability=True)
test.load_from_file("./model2")

In [ ]:
model4 = SVC(kernel='rbf', C= 1, random_state=0, gamma=0.01 )
model4.fit(x_train2, y_train2)

In [28]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.001 )
# linear, rbf, poly
#model.fit(x_train, y_train.values.ravel())
model.fit(x_train, y_train)

SVC(C=10, cache_size=None, class_weight={}, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma=0.001, gpu_id=0,
  kernel='rbf', max_iter=-1, max_mem_size=-1, n_jobs=-1, probability=False,
  random_state=0, shrinking=False, tol=0.001, verbose=False)

In [29]:
model_test_acc(model)

Accuracy: 0.50
[[    0 45058]
 [    0 44942]]


In [30]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.01 )
model.fit(x_train, y_train)
model_test_acc(model)

Accuracy: 0.50
[[    0 45058]
 [    0 44942]]


In [31]:
model = SVC(kernel='rbf', C= 10, random_state=0, gamma=0.1 )
model.fit(x_train, y_train)
model_test_acc(model)

Accuracy: 0.50
[[    0 45058]
 [    0 44942]]
